#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso immiscibleIncompressibleTwoPhaseMixturePsi
wclean libso interfacePropertiesPsi
wclean libso twoPhasePropertiesPsi
wclean

#------------------------------------------------------------------------------
